name: Formatting Checks

on:
  push:
  pull_request:

jobs:
  spellcheck:
    name: Check for formatting errors
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Run formatting checks
        run: |
          bun install
          bun run format
